In [1]:
import numpy as np # Alias 'np' 

In [4]:
#Lets Create a List and Convert it into Numpy Array(nd-array)
myPythonList= [1,3,5,7,9]

np_arr = np.array(myPythonList) # np.array() used to convert arg into np array

np_arr.dtype # in case if you want to know the type
type(np_arr)

numpy.ndarray

In [5]:
# Theory of Less Memory Consumption By Numpy Arrray 

In [6]:
# i am going to create 2 list in python and add them
# i am going to create 2 array in numpy and add them 
# we will count the time difference in millisecond in both the cases.
# 1000 ms in 1 sec.

In [7]:
import time # gives you power to control time 
SIZE=1000000 # 1 Million

p_list1=range(SIZE) # just create a list of 1 million numbers
p_list2=range(SIZE) # just created another list of 1 million numbers

#i just create two numpy array to be added further..

np_list1=np.arange(SIZE)
np_list2=np.arange(SIZE) 



#lets create time tracker

start= time.time()  # returns number of seconds happened after 1 jan 1970

result = [(x+y) for x,y in zip(p_list1,p_list2)] #zip extracts value(one by one) from both the list

#result is the adddition of two list

stop=time.time() # end time 

p_time=(stop-start)*1000

#lets add numpy arrays

start=time.time() # starts for numpy

result =np_list1+np_list2

stop=time.time() # ends for numpy

n_time=(stop-start)*1000

print("Python took ",p_time ," milliseconds")
print("Numpy took ",n_time," milliseconds")


Python took  194.49973106384277  milliseconds
Numpy took  25.92945098876953  milliseconds


In [11]:
# memory Occupancy Test - Python vs Numpy
import sys

In [12]:
python_list = range(1000) # a list of 1000 numbers

no_of_items=len(python_list)
total_size= sys.getsizeof(5)*no_of_items #getsizeof returns size of arg in bytes

print("Total Size occupied ",total_size," bytes")



Total Size occupied  28000  bytes


In [16]:
np_list=np.arange(1000)

np_list.itemsize #individual item size

np_tot_size= np_list.size*np_list.itemsize

print("Total Size occupied ",total_size," bytes")
print("Total Size Occupied in Numpy ",np_tot_size, " bytes")

Total Size occupied  28000  bytes
Total Size Occupied in Numpy  4000  bytes


In [ ]:
#Lets do some fun

In [18]:
#Lets create repeating sequences
a=[1,2,3]
np.tile(a,4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [19]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3])

In [ ]:
# Random Selections 

In [20]:
gifts=["Pen Drive","Laptop","PS4","IPhone","EarPhone"]

In [33]:
np.random.choice(gifts,size=3,p=[0.2,0.3,0.1,0.3,0.1]) 

array(['Pen Drive', 'IPhone', 'Laptop'], dtype='<U9')

In [ ]:
#Reshape and Flatten Data  - 2D array in Action

In [35]:
e = np.array([(1,2,3),(4,5,6)])
e

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
e.shape #(dimensionality)

(2, 3)

In [37]:
e.flatten() # flats the array or 1 D

array([1, 2, 3, 4, 5, 6])

In [40]:
e.reshape(3,2) # 3 Rows 2 columns

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# Testing

a = np.array([1,2,3,4,5])
print(type(a))
print(a.dtype)
print(a.shape)
print(a[0],a[1],a[2])
a[0]=5
print(a)


b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])


In [ ]:
# Some Slicing and chopping in Numpy Arrays!! Numpy CHEF

In [44]:
e = np.array([(1,2,3),(4,5,6)])
print(e)
#print(e[0])

[[1 2 3]
 [4 5 6]]


In [45]:
e[:,1] #  [rows , column]  , : All rows

array([2, 5])

In [48]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
#target is the first row  [5,6,7,8]  <- all columns and only 1 index row
a[1,:]

array([5, 6, 7, 8])

In [50]:
# 1,2 5,6 9,10

a[:,0:2] # [0:2]             start-> (end-1)

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [51]:
# Lets Do Filtering


In [52]:
arr_rand=np.array([8,8,3,7,7,0,4,2,5])

print("Hola! some random Numbers ",arr_rand)

Hola! some random Numbers  [8 8 3 7 7 0 4 2 5]


In [53]:
#lets do some filtering > lets find the numbers greater then 5
indexes = np.where(arr_rand>5)

In [54]:
indexes

(array([0, 1, 3, 4], dtype=int64),)

In [55]:
arr_rand[indexes]

array([8, 8, 7, 7])

In [58]:
eng_choice = np.where(arr_rand>5,"gt5","lt5")

In [59]:
eng_choice # 9 elements i can reshape it to 3X3

array(['gt5', 'gt5', 'lt5', 'gt5', 'gt5', 'lt5', 'lt5', 'lt5', 'lt5'],
      dtype='<U3')

In [60]:
eng_choice.reshape(3,3)

array([['gt5', 'gt5', 'lt5'],
       ['gt5', 'gt5', 'lt5'],
       ['lt5', 'lt5', 'lt5']], dtype='<U3')

In [61]:
np.random.randint(1,100,size=50)

array([37, 94, 55, 87, 78, 86, 87, 61, 16, 98, 62, 17, 14, 80, 26,  7,  9,
       62, 88, 12, 33, 80, 37, 54, 19, 13, 66, 55, 45, 69, 37, 38, 41, 24,
       28, 98, 28, 32, 19, 92, 91, 61, 31, 32, 77, 19, 93, 10,  1, 82])

In [ ]:
#Sorting  of Array

In [62]:
x = np.array([1,3,5,2,4])
x

array([1, 3, 5, 2, 4])

In [65]:
sorted_indexes = np.argsort(x)
sorted_indexes.astype("int16")

In [66]:
sorted_indexes

array([0, 3, 1, 4, 2], dtype=int64)

In [67]:
x[sorted_indexes]

array([1, 2, 3, 4, 5])

In [ ]:
# Quick Sorting in 2D Array

In [69]:
arr = np.random.randint(1,6,size=[8,4])

In [70]:
arr

array([[2, 5, 5, 2],
       [1, 5, 1, 2],
       [2, 5, 2, 1],
       [2, 5, 4, 1],
       [2, 3, 2, 1],
       [3, 1, 3, 2],
       [1, 3, 5, 4],
       [1, 1, 4, 2]])

In [71]:
sorted_indexes = arr[:,0].argsort() # it returns the index of specified column in sorted order

sorted_indexes

array([1, 6, 7, 0, 2, 3, 4, 5], dtype=int64)

In [72]:
arr[sorted_indexes]

array([[1, 5, 1, 2],
       [1, 3, 5, 4],
       [1, 1, 4, 2],
       [2, 5, 5, 2],
       [2, 5, 2, 1],
       [2, 5, 4, 1],
       [2, 3, 2, 1],
       [3, 1, 3, 2]])